name: 'GEORGI_HW'
version: '1.0.0'
require-dbt-version: ">=1.0.0"
profile: 'GEORGI_HW'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  GEORGI_HW:
    staging:
      +materialized: table
      +schema: staging

    transformation:
      +materialized: table
      +schema: transformation

    reporting:
      +materialized: table
      +schema: reporting
